/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AuctionStatus = "cancelled" | "created" | "live" | "settled";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Auctions {
  auction_id: Numeric;
  contract_address: string;
  created_at: Generated<Timestamp>;
  created_block: Generated<Int8>;
  current_bid: Numeric | null;
  current_bidder_address: string | null;
  end_time: Timestamp;
  last_event_block: Int8;
  nft_contract_address: string;
  reserve_price: Numeric;
  seller_address: string;
  start_time: Timestamp;
  status: Generated<AuctionStatus>;
  token_id: Numeric;
  updated_at: Generated<Timestamp>;
  winner_address: string | null;
}

export interface Bids {
  amount: Numeric;
  auction_id: Numeric;
  bidder_address: string;
  block_number: Int8;
  block_time: Timestamp;
  contract_address: string;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  log_index: number;
  tx_hash: string;
}

export interface IndexerState {
  contract_address: string;
  last_block_hash: string;
  last_block_number: Int8;
  updated_at: Generated<Timestamp>;
}

export interface Nfts {
  contract_address: string;
  metadata: Json | null;
  owner_address: string | null;
  token_id: Numeric;
  token_uri: string | null;
  updated_at: Generated<Timestamp>;
}

export interface Outbox {
  created_at: Generated<Timestamp>;
  event_key: string;
  id: Generated<Int8>;
  payload: Json;
  published_at: Timestamp | null;
  topic: string;
}

export interface Users {
  created_at: Generated<Timestamp>;
  wallet_address: string;
}

export interface Watchlist {
  auction_id: Numeric;
  contract_address: string;
  created_at: Generated<Timestamp>;
  wallet_address: string;
}

export interface DB {
  auctions: Auctions;
  bids: Bids;
  indexer_state: IndexerState;
  nfts: Nfts;
  outbox: Outbox;
  users: Users;
  watchlist: Watchlist;
}
